[package]
name = "axum"
version = "0.2.0"
authors = ["Dragos Varovici <dvarovici.work@gmail.com>"]
edition = "2021"

[[bin]]
name = "axum"
path = "src/main.rs"

[[bin]]
name = "axum-sqlx"
path = "src/main_sqlx.rs"

[[bin]]
name = "axum-pg-pool"
path = "src/main_pg_pool.rs"

[[bin]]
name = "axum-mongo"
path = "src/main_mongo.rs"

[[bin]]
name = "axum-mongo-raw"
path = "src/main_mongo_raw.rs"

[[bin]]
name = "axum-pg"
path = "src/main_pg.rs"

[dependencies]
axum = { version = "0.6.1", default-features = false, features = ["json", "query", "headers", "http1", "tokio"] }
deadpool = { version = "0.9.5", features = ["rt_tokio_1", "serde", "async-trait", "managed" ] }
deadpool-postgres = "0.10.3"
dotenv = "0.15.0"
futures = "0.3.25"
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["http1", "server"] }
mongodb = { version = "2.3.1", features = ["zstd-compression", "snappy-compression", "zlib-compression"] }
num_cpus = "1.14.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
sqlx = { version = "0.6.2", features = ["postgres", "macros", "runtime-tokio-native-tls"] }
tokio = { version = "1.24.2", features = ["full"] }
tokio-pg-mapper = "0.2.0"
tokio-pg-mapper-derive = "0.2.0"
tokio-postgres = "0.7.7"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.4.0", features = ["set-header"] }
yarte = "0.15.7"

[profile.release]
lto = true
codegen-units = 1
