[package]
name = "ntex"
version = "0.2.0"
edition = "2018"

[[bin]]
name = "ntex"
path = "src/main.rs"

[[bin]]
name = "ntex-db"
path = "src/main_db.rs"

[[bin]]
name = "ntex-raw"
path = "src/main_raw.rs"

[[bin]]
name = "ntex-sailfish"
path = "src/main_sailfish.rs"

[dependencies]
ntex = "0.2.0-b.4"
mimalloc = { version = "0.1.21", default-features = false }
yarte = { version = "0.14", features = ["bytes-buf", "json"] }
env_logger = "0.8"
random-fast-rng = "0.1.1"
bytes = "0.5.6"
atoi = "0.3.2"
num_cpus = "1.13"
futures = "0.3.12"
http = "0.2"
smallvec = "1.6.1"
simd-json = "0.3.23"
simd-json-derive = "0.1.15"
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4", features = ["release_max_level_off"] }
tokio = "=0.2.6"
tokio-postgres = { git="https://github.com/fafhrd91/postgres.git" }
sailfish = "0.3.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
