[framework]
name = "oxpecker"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.fortune = "/fortunes"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
approach = "Realistic"
classification = "fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"