[framework]
name = "hamlet"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.cached_query = "/cached-worlds?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"

[workerman]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "workerman"
webserver = "none"
versus = "workerman"

[swoole]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "mysql"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "swoole"
webserver = "none"
versus = "swoole"
