[framework]
name = "hapi"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[nginx]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "nginx"
versus = "nodejs"

[postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[mysql]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"
