micronaut:
  application:
    name: micronaut-benchmark
  server:
    port: 8080
    server-header: Micronaut
    date-header: false
    validate-url: false
    netty:
      parent:
        event-loop-group: default
        prefer-native-transport: true
      worker:
        event-loop-group: default
        prefer-native-transport: true
  http:
    client:
      event-loop-group: default
  netty:
    event-loops:
      default:
        prefer-native-transport: true

netty:
  resource-leak-detector-level: DISABLED
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: 512
    transaction-per-operation: false
    allow-connection-per-operation: true

r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 0 # https://github.com/micronaut-projects/micronaut-data/issues/2136
        maxSize: 512

mongodb:
  package-names:
    benchmark
  uuid-representation: STANDARD
