[framework]
name = "iron"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortune"
urls.cached_query = "/cached-worlds?queries="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "Rust"
webserver = "hyper"
versus = ""
