datasource:
  url: jdbc:mysql://tfb-database:3306/hello_world?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  username: benchmarkdbuser
  password: benchmarkdbpass

logging:
  level:
    root: OFF

server:
  http2:
    enabled: false
  netty:
    acceptor-threads: 8
    worker-threads: 16
    max-connection: 10240000
    validate-headers: false
    auto-read: ${server.http2.enabled}
  use-virtual-thread-service-executor: true
