[package]
name = "vortex-template"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Compile-time HTML template engine for Vortex"

[dependencies]
itoa = { workspace = true }
