[framework]
name = "treefrog"

[main]
urls.plaintext = "/world/plain"
urls.json = "/json/json"
urls.db = "/world/random"
urls.query = "/world/queries/"
urls.update = "/world/updates/"
urls.fortune = "/fortune/index"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "None"
webserver = "None"
versus = ""

[mongodb]
urls.plaintext = "/world/plain"
urls.json = "/json/json"
urls.db = "/world/mrandom"
urls.query = "/world/mqueries/"
urls.update = "/world/mupdates/"
urls.fortune = "/fortune/mindex"
approach = "Realistic"
classification = "Fullstack"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "None"
webserver = "None"
versus = "treefrog"

[postgres]
urls.plaintext = "/world/plain"
urls.json = "/json/json"
urls.db = "/world/random"
urls.query = "/world/queries/"
urls.update = "/world/updates/"
urls.fortune = "/fortune/index"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "None"
webserver = "None"
versus = ""

[epoll]
urls.plaintext = "/world/plain"
urls.json = "/json/json"
urls.db = "/world/random"
urls.query = "/world/queries/"
urls.update = "/world/updates/"
urls.fortune = "/fortune/index"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "None"
webserver = "None"
versus = ""
