[framework]
name = "hserver-business"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
orm = "Full"
platform = "hserver-business"
webserver = "hserver-business"
versus = "hserver"
