[framework]
name = "fastpysgi"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "WSGI"
webserver = "FastPySGI"
versus = "wsgi"

[asgi]
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.cached_query = "/cached-queries?count="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "ASGI"
webserver = "FastPySGI"
versus = "uvicorn"
