[package]
name = "xitca-web"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xitca-web"
path = "./src/main.rs"
required-features = ["io-uring", "pg", "router", "template", "zero-copy"]

[[bin]]
name = "xitca-web-compio"
path = "./src/main_compio.rs"
required-features = ["compio", "perf", "perf-json", "pg", "router", "template", "zero-copy"]

[[bin]]
name = "xitca-web-barebone"
path = "./src/main_barebone.rs"
required-features = ["perf", "perf-json", "pg", "template", "zero-copy"]

[[bin]]
name = "xitca-web-diesel"
path = "./src/main_orm.rs"
required-features = ["diesel", "perf", "template", "web-codegen"]

[[bin]]
name = "xitca-web-toasty"
path = "./src/main_orm.rs"
required-features = ["perf", "template", "toasty", "web-codegen"]

[features]
# pg client optional
pg = ["dep:xitca-postgres"]
# diesel orm optional
diesel = ["dep:diesel", "dep:xitca-postgres-diesel", "futures-util/alloc"]
# toasty orm optional
toasty = ["dep:toasty", "dep:xitca-postgres-toasty", "futures-util/alloc"]
# http router optional
router = ["xitca-http/router"]
# web with macros optional
web-codegen = ["xitca-web/codegen", "xitca-web/urlencoded"]
# template optional
template = ["dep:sailfish"]
# io-uring optional
io-uring = ["xitca-http/io-uring", "xitca-server/io-uring"]
# zero-copy database row parsing optional(not supported by ORMs)
zero-copy = []
# unrealistic performance optimization
perf = ["perf-allocator", "dep:core_affinity", "tokio/parking_lot"]
perf-allocator = ["dep:mimalloc"]
# regular json serializer
json = ["serde_json"]
# performance optimization json serializer
perf-json = ["sonic-rs"]
# compio as runtime
compio = ["dep:compio", "dep:socket2", "xitca-http/compio", "xitca-postgres/compio"]

[dependencies]
xitca-http = "0.8.2"
xitca-io = "0.5.1"
xitca-server = "0.6.1"
xitca-service = "0.3"
xitca-unsafe-collection = "0.2"

atoi = "2"
httparse = "1"
serde_core = { version = "1" }

# web optional
xitca-web = { version = "0.8", features = ["json"], optional = true }

# raw-pg optional
xitca-postgres = { version = "0.4", optional = true }

# diesel orm optional
diesel = { version = "2", features = ["postgres"], optional = true }
xitca-postgres-diesel = { version = "0.3", default-features = false, optional = true }
futures-util = { version = "0.3", default-features = false, optional = true }

# toasty orm optional
xitca-postgres-toasty = { version = "0.1", features = ["nightly"], optional = true }
toasty = { version = "0.1", optional = true }

# template optional
sailfish = { version = "0.10", default-features = false, features = ["perf-inline"], optional = true }

# perf optional
core_affinity = { version = "0.8.1", optional = true }
mimalloc = { version = "0.1", default-features = false, optional = true }

# json optioanl
serde_json = { version = "1", optional = true }
sonic-rs = { version = "0.5.6", optional = true }

# compio optional
compio = { version = "0.17", features = ["time"], optional = true }
socket2 = { version = "0.6", optional = true }

futures-core = { version = "0.3", default-features = false }
rand = { version = "0.9", features = ["os_rng", "small_rng"], default-features = false }
tokio = "1.48"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[patch.crates-io]
xitca-postgres-diesel = { git = "https://github.com/fakeshadow/xitca-postgres-diesel", rev = "9fab3a8" }
xitca-postgres-toasty = { git = "https://github.com/fakeshadow/xitca-postgres-toasty", rev = "f410f04" }

toasty = { git = "https://github.com/fakeshadow/toasty", rev = "0edc941" }
toasty-core = { git = "https://github.com/fakeshadow/toasty", rev = "0edc941" }
toasty-sql = { git = "https://github.com/fakeshadow/toasty", rev = "0edc941" }

xitca-postgres = { git = "http://github.com/HFQR/xitca-web", rev = "e1c8c7b" }
xitca-router = { git = "http://github.com/HFQR/xitca-web", rev = "e1c8c7b" }
xitca-web = { git = "http://github.com/HFQR/xitca-web", rev = "e1c8c7b" }
