[package]
name = "xitca-web"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "xitca-web"
path = "./src/main.rs"

[[bin]]
name = "xitca-web-diesel"
path = "./src/main_diesel.rs"

[dependencies]
xitca-http = { git = "https://github.com/fakeshadow/xitca-web.git", rev = "06474415418a12451f7910b88784cc5d9205983e" }
xitca-web = { git = "https://github.com/fakeshadow/xitca-web.git", rev = "06474415418a12451f7910b88784cc5d9205983e" }

ahash = { version = "0.7.4", features = ["compile-time-rng"] }
atoi = "0.4.0"
bytes = "1"
core_affinity = "0.5.10"
diesel = { version = "1.4.7", features = ["postgres", "r2d2"] }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
mimalloc = { version = "0.1.25", default-features = false }
rand = { version = "0.8", default-features = false, features = ["min_const_gen", "small_rng"] }
sailfish = "0.3.3"
serde = "1"
simd-json = "0.4.6"
tokio = { version = "1.7", features = ["macros", "rt"] }
tokio-postgres = "0.7.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[patch.crates-io]
xitca-http = { git = "https://github.com/fakeshadow/xitca-web.git", rev = "06474415418a12451f7910b88784cc5d9205983e" }
xitca-server = { git = "https://github.com/fakeshadow/xitca-web.git", rev = "06474415418a12451f7910b88784cc5d9205983e" }
xitca-service = { git = "https://github.com/fakeshadow/xitca-web.git", rev = "06474415418a12451f7910b88784cc5d9205983e" }
