[package]
name = "xitca-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xitca-web"
path = "./src/main.rs"
required-features = ["io-uring", "pg", "router", "template"]

[[bin]]
name = "xitca-web-iou"
path = "./src/main_iou.rs"
required-features = ["io-uring", "perf", "pg", "template"]

[[bin]]
name = "xitca-web-wasm"
path = "./src/main_wasm.rs"
required-features = ["web"]

[[bin]]
name = "xitca-web-axum"
path = "./src/main_axum.rs"
required-features = ["axum", "io-uring", "perf", "pg-sync", "template"]

[[bin]]
name = "xitca-web-sync"
path = "./src/main_sync.rs"
required-features = ["pg-orm", "template", "web-codegen"]

[features]
# pg optional
pg = ["dep:xitca-postgres"]
# pg send/sync optional
pg-sync = ["dep:xitca-postgres"]
# pg orm optional
pg-orm = ["dep:diesel"]
# http router optional
router = ["xitca-http/router"]
# web optional
web = ["dep:xitca-web"]
# web codegen optional
web-codegen = ["xitca-web/codegen", "xitca-web/urlencoded"]
# template optional
template = ["dep:sailfish"]
# io-uring optional
io-uring = ["xitca-http/io-uring", "xitca-server/io-uring"]
# axum optional
axum = ["dep:axum", "dep:http-body", "dep:tower", "dep:tower-http", "xitca-web/tower-http-compat" ]
# unrealistic performance optimization
perf = ["dep:mimalloc", "tokio/parking_lot"]

[dependencies]
xitca-http = "0.6"
xitca-io = "0.4"
xitca-server = "0.4"
xitca-service = "0.2"
xitca-unsafe-collection = "0.2"

atoi = "2"
serde = { version = "1" }
serde_json = { version = "1" }

# web optional
xitca-web = { version = "0.6", features = ["json"], optional = true }

# raw-pg optional
xitca-postgres = { version = "0.1", optional = true }

# orm optional
diesel = { version = "2", features = ["postgres", "r2d2"], optional = true }

# template optional
sailfish = { version = "0.9", default-features = false, features = ["derive", "perf-inline"], optional = true }

# axum optional
axum = { version = "0.7", optional = true, default-features = false, features = ["json", "query"] }
http-body = { version = "1", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["set-header"], optional = true }

# perf optional
mimalloc = { version = "0.1", default-features = false, optional = true }

# stuff can not be used or not needed in wasi target
[target.'cfg(not(target_family = "wasm"))'.dependencies]
futures-core = { version = "0.3", default-features = false }
nanorand = { version = "0.7", default-features = false, features = ["tls"] }
tokio = "1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[patch.crates-io]
xitca-postgres = { git = "https://github.com/HFQR/xitca-web.git", rev = "9835c0b" }
mio = { git = "https://github.com/fakeshadow/mio", rev = "9bae6012b7ecfc6083350785f71a5e8265358178" }
