[package]
name = "xitca-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xitca-web"
path = "./src/main.rs"
required-features = ["io-uring", "pg", "router", "template"]

[[bin]]
name = "xitca-web-iou"
path = "./src/main_iou.rs"
required-features = ["io-uring", "pg-iou", "template"]

[[bin]]
name = "xitca-web-wasm"
path = "./src/main_wasm.rs"
required-features = ["web"]

[features]
# pg optional
pg = ["xitca-postgres"]
# pg io_uring optional
pg-iou = ["xitca-postgres/io-uring"]
# http router optional
router = ["xitca-http/router"]
# web optional
web = ["xitca-web"]
# template optional
template = ["sailfish"]
# io-uring optional
io-uring = ["xitca-http/io-uring", "xitca-server/io-uring"]

[dependencies]
xitca-http = "0.1"
xitca-io = "0.1"
xitca-server = "0.1"
xitca-service = "0.1"
xitca-unsafe-collection = "0.1"

atoi = "2"
serde = { version = "1" }
serde_json = { version = "1" }

# web optional
xitca-web = { version = "0.1", features = ["json"], optional = true }

# raw-pg optional
xitca-postgres = { version = "0.1", features = ["single-thread"], optional = true }

# template optional
sailfish = { version = "0.8", default-features = false, features = ["derive", "perf-inline"], optional = true }

# stuff can not be used or not needed in wasi target
[target.'cfg(not(target_family = "wasm"))'.dependencies]
futures-core = { version = "0.3", default-features = false }
mimalloc = { version = "0.1", default-features = false }
nanorand = { version = "0.7", default-features = false, features = ["tls"] }
tokio = "1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[patch.crates-io]
xitca-http = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-io = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-postgres = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-router = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-server = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-service = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-unsafe-collection = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }
xitca-web = { git = "https://github.com/HFQR/xitca-web.git", rev = "816666053f01c2b21beb847e25d65477f7e09c3d" }

mio = { git = "https://github.com/fakeshadow/mio.git", rev = "eb67f6794edba8bc2e973ddef32e066b41ff812a" }
