[package]
name = "xitca-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xitca-web"
path = "./src/main.rs"
required-features = ["pg", "serde", "template"]

[[bin]]
name = "xitca-web-diesel"
path = "./src/main_diesel.rs"
required-features = ["pg-orm", "serde", "template", "web"]

[[bin]]
name = "xitca-web-iou"
path = "./src/main_iou.rs"
required-features = ["io-uring", "pg", "serde", "template"]

[[bin]]
name = "xitca-web-epoll"
path = "./src/main_iou.rs"
required-features = ["pg", "serde", "template"]

[[bin]]
name = "xitca-web-wasm"
path = "./src/main_wasm.rs"
required-features = ["web"]

[features]
# pg optional
pg = ["xitca-postgres"]
# pg orm optional
pg-orm = ["diesel", "diesel-async", "tang-rs"]
# serde optional
serde = ["dep:serde", "serde_json"]
# web optional
web = ["xitca-web"]
# template optional
template = ["sailfish"]
# io-uring optional
io-uring = ["tokio-uring", "xitca-server/io-uring"]

[dependencies]
xitca-http = { version = "0.1", features = ["util-service"] }
xitca-io = "0.1"
xitca-server = "0.1"
xitca-service = "0.1"
xitca-unsafe-collection = "0.1"

atoi = "2"

# web optional
xitca-web = { version = "0.1", features = ["json"], optional = true }

# raw-pg optional
xitca-postgres = { version = "0.1", features = ["single-thread"], optional = true }

# diesel-pg orm optional
diesel = { version = "2", default-features = false, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"], optional = true }
diesel-async = { version = "0.2", default-features = false, features = ["postgres"], optional = true }
tang-rs = { version = "0.2", optional = true }

# serde optional
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }

# io-uring optional
tokio-uring = { version = "0.4", features = ["bytes"], optional = true }

# template optional
sailfish = { version = "0.6", optional = true }

# stuff can not be used or not needed in wasi target
[target.'cfg(not(target_family = "wasm"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
nanorand = { version = "0.7", default-features = false, features = ["tls"] }
tokio = "1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[patch.crates-io]
xitca-http = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-io = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-postgres = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-router = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-server = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-service = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-unsafe-collection = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }
xitca-web = { git = "https://github.com/HFQR/xitca-web.git", rev = "d3e9a4fb6b16513ff638f43305c9c96cdb3501b2" }

mio = { git = "https://github.com/fakeshadow/mio.git", rev = "4272250caed2f460f7be646d0fd25d53d267eb53" }
