server:
  server-header: Spring
  servlet:
    encoding:
      force: true
---
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}?loggerLevel=OFF&disableColumnSanitiser=true&assumeMinServerVersion=16&sslmode=disable
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 512
database:
  name: hello_world
  host: tfb-database
  port: 5432
  username: benchmarkdbuser
  password: benchmarkdbpass

---
spring:
  config:
    activate:
      on-profile: mongo
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

spring.data.mongodb:
  host: tfb-database
  port: 27017
  database: hello_world

---
spring:
  profiles:
    active: jdbc
