[framework]
name = "oxygen.jl"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "None"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "None"
webserver = "Oxygen.jl"
versus = ""
