[package]
name    = "framework_benchmarks-glommio"
version = "0.0.0"
edition = "2024"
authors = ["kanarus <kanarus786@gmail.com>"]

[profile.release]
lto           = true
panic         = "abort"
codegen-units = 1

[dependencies]
framework_benchmarks = { path = "..", features = ["rt_glommio"] }
glommio              = { version = "0.9" }
num_cpus             = { version = "1.17" }
