[framework]
name = "falcon"

[main]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "Meinheld"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [Meinheld]"
notes = "cythonized"
versus = "wsgi"

[bjoern]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "bjoern"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [Bjoern]"
notes = ""
versus = "wsgi"

[waitress]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "waitress"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [Waitress]"
notes = ""
versus = "wsgi"

[orjson]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "Meinheld"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [Meinheld-Orjson]"
notes = "cythonized+orjson"
versus = "wsgi"

[socketify-wsgi]
json.url = "/json"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "Socketify.py"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [socketify.py WSGI]"
notes = "cythonized"
versus = "wsgi"

[socketify-asgi]
json.url = "/json"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "ASGI"
webserver = "Socketify.py"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [socketify.py ASGI]"
notes = "cythonized"
versus = "asgi"

[socketify-asgi-pypy3]
json.url = "/json"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "PyPy3"
orm = "Full"
platform = "ASGI"
webserver = "Socketify.py"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [socketify.py ASGI Pypy3]"
notes = ""
versus = "asgi"

[socketify-wsgi-pypy3]
json.url = "/json"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "PyPy3"
orm = "Full"
platform = "WSGI"
webserver = "Socketify.py"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [socketify.py WSGI Pypy3]"
notes = ""
versus = "wsgi"

[pypy3]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "PyPy3"
orm = "Full"
platform = "WSGI"
webserver = "Gunicorn"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [Pypy3]"
notes = ""
versus = "wsgi"

[asgi]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "ASGI"
webserver = "Uvicorn"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [ASGI/Tortoise]"
notes = ""
versus = "uvicorn"

[fastwsgi]
json.url = "/json"
db.url = "/db"
query.url = "/queries/"
update.url = "/updates/"
fortune.url = "/fortunes"
plaintext.url = "/plaintext"
port = 8080
approach = "Realistic"
classification = "Micro"
database = "Postgres"
framework = "Falcon"
language = "Python"
flavor = "Python3"
orm = "Full"
platform = "WSGI"
webserver = "FastWSGI"
os = "Linux"
database.os = "Linux"
display.name = "Falcon [FastWSGI]"
notes = ""
versus = "wsgi"
