[framework]
name = "vapor"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database_os = "Linux"
os = "Linux"
platform = "None"
webserver = "None"
versus = "None"

[fluent]
urls.db = "/db"
urls.query = "/queries?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "None"
webserver = "None"
versus = "None"

[postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "None"
versus = "None"

[sql-kit]
urls.db = "/db"
urls.query = "/queries?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "None"
webserver = "None"
versus = "None"
