[framework]
name = "aspnetcore"

[ado-pg]
urls.db = "/db"
urls.query = "/queries/"
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds/"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[ado-my]
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds/"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-my"

[mw-ef-pg]
urls.db = "/db/ef"
urls.query = "/queries/ef?queries="
urls.fortune = "/fortunes/ef"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mvc-ef-pg]
urls.db = "/mvc/db/ef"
urls.query = "/mvc/queries/ef?queries="
urls.fortune = "/mvc/fortunes/ef"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw-json]
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"

[mvc]
urls.plaintext = "/mvc/plaintext"
urls.json = "/mvc/json"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"

[mw-ado-pg]
urls.db = "/db/raw"
urls.query = "/queries/raw?queries="
urls.fortune = "/fortunes/raw"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mvc-ado-pg]
urls.db = "/mvc/db/raw"
urls.query = "/mvc/queries/raw?queries="
urls.fortune = "/mvc/fortunes/raw"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw-ado-my]
urls.db = "/db/raw"
urls.query = "/queries/raw?queries="
urls.update = "/updates/raw?queries="
urls.fortune = "/fortunes/raw"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-my"

[mvc-ado-my]
urls.db = "/mvc/db/raw"
urls.query = "/mvc/queries/raw?queries="
urls.update = "/mvc/updates/raw?queries="
urls.fortune = "/mvc/fortunes/raw"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-my"

[mvc-ado-pg-up]
urls.update = "/mvc/updates/raw?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw-ado-pg-up]
urls.update = "/updates/raw?queries="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mvc-dap-pg]
urls.db = "/mvc/db/dapper"
urls.query = "/mvc/queries/dapper?queries="
urls.fortune = "/mvc/fortunes/dapper"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw-dap-pg]
urls.db = "/db/dapper"
urls.query = "/queries/dapper?queries="
urls.fortune = "/fortunes/dapper"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mvc-dap-my]
urls.db = "/mvc/db/dapper"
urls.query = "/mvc/queries/dapper?queries="
urls.update = "/mvc/updates/dapper?queries="
urls.fortune = "/mvc/fortunes/dapper"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-my"

[mw-dap-my]
urls.db = "/db/dapper"
urls.query = "/queries/dapper?queries="
urls.update = "/updates/dapper?queries="
urls.fortune = "/fortunes/dapper"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-my"

[mw-ef-pg-up]
urls.update = "/updates/ef?queries="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mvc-ef-pg-up]
urls.update = "/mvc/updates/ef?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"

[mvc-dap-pg-up]
urls.update = "/mvc/updates/dapper?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw-dap-pg-up]
urls.update = "/updates/dapper?queries="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg"

[mw]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore"

[ado-pg-up]
urls.update = "/updates/"
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspcore-ado-pg-up"
