production:
  adapter: trilogy
  encoding: utf8
  host: tfb-database
  database: hello_world
  username: benchmarkdbuser
  password: benchmarkdbpass
  pool: <%= ENV.fetch('MAX_THREADS') %>
  timeout: 5000
  ssl: true
  ssl_mode: 4 <%# Trilogy::SSL_PREFERRED_NOVERIFY %>
  tls_min_version: 3 <%# Trilogy::TLS_VERSION_12 %>
