production:
  adapter: postgresql
  encoding: utf8
  host: tfb-database
  database: hello_world
  username: benchmarkdbuser
  password: benchmarkdbpass
  pool: <%= ENV.fetch('MAX_THREADS') %>
  timeout: 5000
  encoding: unicode
