[framework]
name = "httpserver"

[main]
urls.plaintext = "/plaintext"
urls.fortune = "/fortunes"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = ""

[graalvm]
urls.plaintext = "/plaintext"
urls.fortune = "/fortunes"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver"


[robaho]
urls.plaintext = "/plaintext"
urls.fortune = "/fortunes"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver"


[robaho-graalvm]
urls.plaintext = "/plaintext"
urls.fortune = "/fortunes"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver-robaho"

[robaho-zgc]
urls.plaintext = "/plaintext"
urls.fortune = "/fortunes"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver-robaho"
