[framework]
name = "ubiquity"

[roadrunner]
urls.plaintext = "/Plaintext_"
urls.json = "/Json_"
urls.db = "/Db_"
urls.query = "/Db_/query/"
urls.update = "/Db_/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "RoadRunner"
webserver = "none"
versus = "php"

[ngx-raw]
urls.db = "/DbRaw"
urls.query = "/DbRaw/query/"
urls.update = "/DbRaw/update/"
urls.fortune = "/FortunesRaw"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "ngx_php"
webserver = "nginx"
versus = "ngx_php"

[swoole]
urls.plaintext = "/Plaintext_"
urls.json = "/Json_"
urls.db = "/Db_"
urls.query = "/Db_/query/"
urls.update = "/Db_/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "swoole"
webserver = "none"
versus = "swoole"

[main]
urls.plaintext = "/Plaintext"
urls.json = "/Json"
urls.db = "/Db"
urls.query = "/Db/query/"
urls.update = "/Db/update/"
urls.fortune = "/Fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"

[ngx]
urls.plaintext = "/Plaintext_"
urls.json = "/Json_"
urls.db = "/Db_"
urls.query = "/Db_/query/"
urls.update = "/Db_/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "ngx_php"
webserver = "nginx"
versus = "ngx_php"

[workerman]
urls.db = "/Db_"
urls.query = "/Db_/query/"
urls.update = "/Db_/update/"
urls.fortune = "/Fortunes_"
urls.cached_query = "/Cache/cachedquery/"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "workerman"
webserver = "none"
versus = "workerman"

[workerman-mysql]
urls.db = "/DbMy"
urls.query = "/DbMy/query/"
urls.update = "/DbMy/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "Mysql"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "workerman"
webserver = "none"
versus = "php"

[workerman-mongo]
urls.db = "/DbMongo"
urls.query = "/DbMongo/query/"
urls.update = "/DbMongo/update/"
urls.fortune = "/FortunesMongo"
approach = "Realistic"
classification = "Fullstack"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "workerman"
webserver = "none"
versus = "php"

[workerman-raw]
urls.plaintext = "/Plaintext_"
urls.json = "/Json_"
urls.db = "/DbRaw"
urls.query = "/DbRaw/query/"
urls.update = "/DbRaw/update/"
urls.fortune = "/FortunesRaw"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "workerman"
webserver = "none"
versus = "php"

[swoole-mysql]
urls.db = "/DbMy"
urls.query = "/DbMy/query/"
urls.update = "/DbMy/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "MYSQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "swoole"
webserver = "none"
versus = "swoole"

[roadrunner-mysql]
urls.db = "/DbMy"
urls.query = "/DbMy/query/"
urls.update = "/DbMy/update/"
urls.fortune = "/Fortunes_"
approach = "Realistic"
classification = "Fullstack"
database = "Mysql"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "RoadRunner"
webserver = "none"
versus = "php"
