[framework]
name = "dropwizard"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/db/query?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "JAX-RS"
webserver = "Jetty"
versus = "servlet-raw"

[mongodb]
urls.db = "/db"
urls.query = "/db/query?queries="
urls.update = "/db/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "JAX-RS"
webserver = "Jetty"
versus = "dropwizard"

[postgres]
urls.db = "/db"
urls.query = "/db/query?queries="
urls.update = "/db/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "JAX-RS"
webserver = "Jetty"
versus = "dropwizard"

[jdbi-postgres]
urls.db = "/db"
urls.query = "/db/query?queries="
urls.update = "/db/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "JAX-RS"
webserver = "Jetty"
versus = "dropwizard"
