[framework]
name = "micronaut"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-vertx-pg-client"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "None"

[jdbc]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-jdbc"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut"

[r2dbc]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-r2dbc"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut"

[data-jdbc]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-data-jdbc"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-jdbc"

[data-r2dbc]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-data-r2dbc"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-r2dbc"

[vertx-pg-client-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-vertx-pg-client-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut"

[jdbc-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-jdbc-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-jdbc"

[r2dbc-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-r2dbc-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-r2dbc"

[data-jdbc-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-data-jdbc-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-data-jdbc"

[data-r2dbc-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
display_name = "micronaut-data-r2dbc-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-data-r2dbc"

[data-mongodb]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
display_name = "micronaut-data-mongodb"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut"

[data-mongodb-graalvm]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
display_name = "micronaut-data-mongodb-graalvm"
os = "Linux"
orm = "raw"
platform = "Netty"
webserver = "None"
versus = "micronaut-data-mongodb"
