_json:
    pattern:  /json
    defaults: { _controller: SkamanderBenchmarkBundle:Bench:json }

_db:
    pattern:  /db
    defaults: { _controller: SkamanderBenchmarkBundle:Bench:db }

_dbRaw:
    pattern:  /db-raw
    defaults: { _controller: SkamanderBenchmarkBundle:Bench:dbRaw }

_fortunes:
    pattern:  /fortunes
    defaults: { _controller: SkamanderBenchmarkBundle:Bench:fortunes }

_fortunesRaw:
    pattern:  /fortunes-raw
    defaults: { _controller: SkamanderBenchmarkBundle:Bench:fortunesRaw }