[framework]
name = "servlet"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Resin"
versus = ""

[lib-native]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Resin"
versus = "servlet"

[postgresql]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds?queries="
approach = "Realistic"
classification = "Platform"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Resin"
versus = "servlet-raw"

[mysql]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Resin"
versus = "None"
