[framework]
name = "voovan"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "Voovan"
webserver = "None"
versus = ""
