# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: hello_world
  username: benchmarkdbuser
  password: benchmarkdbpass
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: hello_world
  username: benchmarkdbuser
  password: benchmarkdbpass
  host: localhost
  pool: 200
  timeout: 5000
