[framework]
name = "ring-http-exchange"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver"

[robaho]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "httpserver-robaho"

[robaho-is]
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "ring-http-exchange-robaho"

[robaho-async]
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "ring-http-exchange-robaho"

[robaho-vertx]
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "httpserver"
webserver = "None"
versus = "ring-http-exchange-robaho-async"