[framework]
name = "express"

[postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database_os = "Linux"
os = "Linux"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[mongodb]
urls.db = "/mongoose"
urls.query = "/mongooseq?queries="
urls.update = "/mongoose-update?queries="
urls.fortune = "/mongoose-fortune"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[mysql]
urls.db = "/mysql-orm"
urls.query = "/mysql-orm-query?queries="
urls.update = "/mysql-orm-update?queries="
urls.fortune = "/mysql-orm-fortune"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "nodejs"
webserver = "None"
versus = "nodejs"

[chakra]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database_os = "Linux"
os = "Linux"
platform = "nodejs"
webserver = "None"
versus = "nodejs"
