[versions]
kotlin = "2.3.0-Beta2"
shadow = "9.2.2"
vertx = "5.0.5"
micrometer = "1.16.0"
netty = "4.2.7.Final"
dsljson = "2.0.2"
log4j = "2.25.2"
log4j-kotlin = "1.5.0"
disruptor = "4.0.0"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Vert.x
vertx-bom = { module = "io.vertx:vertx-stack-depchain", version.ref = "vertx" }
vertx-core = { module = "io.vertx:vertx-core" }
vertx-web = { module = "io.vertx:vertx-web" }
vertx-pg-client = { module = "io.vertx:vertx-pg-client" }
vertx-lang-kotlin = { module = "io.vertx:vertx-lang-kotlin" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines" }
vertx-micrometer = { module = "io.vertx:vertx-micrometer-metrics" }

# Prometheus
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

# Netty
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }

# DSL-JSON
dsl-json = { module = "com.dslplatform:dsl-json", version.ref = "dsljson" }

# Logging
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-api-kotlin = { module = "org.apache.logging.log4j:log4j-api-kotlin", version.ref = "log4j-kotlin" }
disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
