[framework]
name = "cutelyst"

[thread-apg-batch]
urls.update = "/updateb?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-pg]
urls.db = "/db_postgres"
urls.query = "/query_postgres?queries="
urls.update = "/updates_postgres?queries="
urls.fortune = "/fortunes_raw_postgres"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-pg-cutelee]
urls.fortune = "/fortunes_cutelee_postgres"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-pico]
urls.json = "/pson"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-apg]
urls.db = "/dbp"
urls.query = "/queriesp?queries="
urls.update = "/updatep?queries="
urls.fortune = "/fortunes_raw_p"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-my]
urls.db = "/db_mysql"
urls.query = "/query_mysql?queries="
urls.update = "/updates_mysql?queries="
urls.fortune = "/fortunes_raw_mysql"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[thread-my-cutelee]
urls.fortune = "/fortunes_cutelee_mysql"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[pf-pg]
urls.db = "/db_postgres"
urls.query = "/query_postgres?queries="
urls.update = "/updates_postgres?queries="
urls.fortune = "/fortunes_raw_postgres"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[pf-apg-batch]
urls.update = "/updateb?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[pf-my]
urls.db = "/db_mysql"
urls.query = "/query_mysql?queries="
urls.update = "/updates_mysql?queries="
urls.fortune = "/fortunes_raw_mysql"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[pf-apg]
urls.db = "/dbp"
urls.query = "/queriesp?queries="
urls.update = "/updatep?queries="
urls.fortune = "/fortunes_raw_p"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""

[t-apg-cutelee]
urls.fortune = "/fortunes_c_p"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "CutelystWSGI"
webserver = "None"
versus = ""
