[framework]
name = "wicket"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/db?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Servlet"
webserver = "Resin"
versus = "servlet"
