
serviceName : Hexagon Benchmark

bindPort : 9090
bindAddress : 0.0.0.0

database : hello_world
worldCollection : world
fortuneCollection : fortune

databaseUsername : benchmarkdbuser
databasePassword : benchmarkdbpass

maximumPoolSize : 64
