[framework]
name = "cuehttp"

[main]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "None"
webserver = "None"
versus = "cuehttp"
