[framework]
name = "watson"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Watson"
versus = "None"
