[package]
name = "actix"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "actix"
path = "src/main.rs"

[[bin]]
name = "actix-platform"
path = "src/main_platform.rs"

[[bin]]
name = "actix-diesel"
path = "src/main_diesel.rs"

[[bin]]
name = "actix-pg"
path = "src/main_pg.rs"

[dependencies]
actix = { version="0.8.0-alpha.2", features=["http"] }
actix-web = { version="1.0.0-alpha.3", default-features = false }
actix-http = { version="0.1.0-alpha.3", default-features = false }
actix-rt = "0.2.2"
actix-server = "0.4.2"
actix-service = "0.3.5"

askama = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
env_logger = "0.6"
rand = "0.5"
bytes = "0.4"
num_cpus = "1.0"
futures = "0.1.25"
http = "0.1"
diesel = { version = "1.2", features = ["postgres"] }
url = { version="1.7", features=["query_encoding"] }
log = { version = "0.4", features = ["release_max_level_off"] }
phf = "0.7.22"
tokio-postgres = { git="https://github.com/fafhrd91/rust-postgres.git" }

[build-dependencies]
askama = "0.8"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1