[package]
name = "actix"
version = "2.0.0"
edition = "2018"

[[bin]]
name = "actix"
path = "src/main.rs"

[[bin]]
name = "actix-platform"
path = "src/main_platform.rs"

[[bin]]
name = "actix-diesel"
path = "src/main_diesel.rs"

[[bin]]
name = "actix-pg"
path = "src/main_pg.rs"

[[bin]]
name = "actix-raw"
path = "src/main_raw.rs"

[dependencies]
actix = { version="0.9.0", features=["http"] }
actix-web = { version="2.0.0", default-features = false }
actix-http = { version="1.0.1", default-features = false }
actix-rt = "1.0.0"
actix-codec = "0.2.0"
actix-server = "1.0.0"
actix-service = "1.0.1"
jemallocator = "0.3.2"
askama = "0.8"
markup = "0.4.1"
yarte = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
env_logger = "0.7"
rand = { version = "0.7", features = ["small_rng"] }
bytes = "0.5.3"
num_cpus = "1.0"
futures = "0.3.1"
http = "0.2"
diesel = { version = "1.4.3", features = ["postgres"] }
url = { version="1.7", features=["query_encoding"] }
log = { version = "0.4", features = ["release_max_level_debug"] }
v_htmlescape = "0.4.5"
tokio = "=0.2.6"
tokio-postgres = { git="https://github.com/fafhrd91/rust-postgres.git" }

[build-dependencies]
askama = "0.8"
bindgen = "0.42"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
