[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[target.aarch64-unknown-linux-gnu]
linker = "clang"
