[framework]
name = "redkale"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.fortune = "/fortunes"
urls.query = "/queries?q="
urls.update = "/updates?q="
urls.cached_query = "/cached-worlds?q="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Redkale"
webserver = "Redkale"
versus = ""

[native]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.fortune = "/fortunes"
urls.query = "/queries?q="
urls.update = "/updates?q="
urls.cached_query = "/cached-worlds?q="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Redkale"
webserver = "Redkale"
versus = "Redkale"

[jdbc]
urls.db = "/db"
urls.fortune = "/fortunes"
urls.query = "/queries?q="
urls.update = "/updates?q="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Redkale"
webserver = "Redkale"
versus = "Redkale"

[pgclient]
urls.db = "/db"
urls.fortune = "/fortunes"
urls.query = "/queries?q="
urls.update = "/updates?q="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Redkale"
webserver = "Redkale"
versus = "Redkale"