[framework]
name = "solon"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "None"
os = "Linux"
orm = "None"
platform = "JVM"
webserver = "smarthttp"
notes = ""
versus = ""