[package]
name = "may-minihttp"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
edition = "2018"

[dependencies]
markup = "0.4"
mimalloc = "0.1"
num_cpus = "1.0"
oorandom = "11"
smallvec = "1.1"
v_htmlescape = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
may = "0.3"
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git" }
may_minihttp = { git = "https://github.com/Xudong-Huang/may_minihttp.git" }

[profile.release]
lto = true
codegen-units = 1

