[package]
name = "may-minihttp"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]

[dependencies]
mimalloc = "0.1"
num_cpus = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
may = "0.3"
may_minihttp = { git = "https://github.com/Xudong-Huang/may_minihttp.git" }

[profile.release]
lto = true
codegen-units = 1
