[framework]
name = "http-kit"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.update = "/updates/"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "Ring"
webserver = "None"
versus = ""
