[framework]
name = "youi"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "None"
platform = "Undertow"
webserver = "None"
versus = "Undertow"
