[framework]
name = "mixphp"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?q="
urls.update = "/update?q="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"

[swoole-mysql]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?q="
urls.update = "/update?q="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "swoole"
webserver = "None"
versus = "swoole"

[workerman-mysql]
urls.db = "/db"
urls.query = "/query?q="
urls.update = "/update?q="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "micro"
platform = "workerman"
webserver = "None"
versus = "workerman"

[workerman-pgsql]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?q="
urls.update = "/update?q="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "workerman"
webserver = "None"
versus = "workerman"