[framework]
name = "grape"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Rack"
webserver = "Puma"
versus = "rack-puma-mri"

[iodine]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/query?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Rack"
webserver = "Iodine"
versus = "rack-iodine-mri"
