[framework]
name = "grizzly"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Servlet"
webserver = "Grizzly"
versus = ""

[jersey]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/db/queries?queries="
urls.update = "/db/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "JAX-RS"
webserver = "Grizzly"
versus = "grizzly"
