[framework]
name = "appmpower"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "kestrel"
versus = "aspnetcore-minimal"

[odbc-pg]
urls.db = "/db"
urls.query = "/queries?c="
urls.update = "/updates?c="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds?c="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspnetcore-minimal"

[ado-pg]
urls.db = "/db"
urls.query = "/queries?c="
urls.update = "/updates?c="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds?c="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = ".NET"
webserver = "Kestrel"
versus = "aspnetcore-minimal"