[framework]
name = "vertx-web"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Vert.x"
webserver = "None"
versus = "vertx"

[mongodb]
urls.db = "/mongo/db"
urls.query = "/mongo/queries?queries="
urls.update = "/mongo/update?queries="
urls.fortune = "/mongo/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Vert.x"
webserver = "None"
versus = ""

[postgres]
urls.db = "/psql/db"
urls.query = "/psql/queries?queries="
urls.update = "/psql/update?queries="
urls.fortune = "/psql/fortunes"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Vert.x"
webserver = "None"
versus = ""
