[package]
name    = "framework_benchmarks-tokio"
version = "0.0.0"
edition = "2024"
authors = ["kanarus <mail@kanarus.dev>"]

[profile.release]
lto           = true
panic         = "abort"
codegen-units = 1

[dependencies]
framework_benchmarks = { path = "..",      features = ["rt_tokio"] }
tokio                = { version = "1.47", features = ["full"] }
