[framework]
name = "stream"

[main]
urls.db = "/db-mongo"
urls.query = "/queries-mongo?queries="
urls.update = "/updates-mongo?queries="
urls.fortune = "/fortunes-mongo"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "nginx"
versus = "dart"
