[framework]
name = "warp-rust"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries/"
urls.fortune = "/fortunes"
urls.update = "/updates/"
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Rust"
webserver = "Hyper"
versus = "None"
