[framework]
name = "phalcon"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/update?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"

[mongodb]
urls.db = "/mongodb/db"
urls.query = "/mongodb/queries?queries="
urls.fortune = "/mongodb/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"

[micro]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "raw"
platform = "FPM/FastCGI"
webserver = "nginx"
versus = "php"
