[framework]
name = "wiredio"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
database_os = "Linux"
orm = "None"
platform = ".NET"
webserver = "Wired.IO"
versus = "None"

[plt]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Platform"
os = "Linux"
database_os = "Linux"
orm = "None"
platform = ".NET"
webserver = "Unhinged"
versus = "None"

[gen]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
os = "Linux"
database_os = "Linux"
orm = "None"
platform = ".NET"
webserver = "Unhinged"
versus = "None"