name: get-maintainers
on: 
  pull_request:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  get_maintainers:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Get commit branch and commit message from PR
        run: |
          echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "TARGET_BRANCH_NAME=$(echo ${GITHUB_BASE_REF##*/})" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$(git log --format=%B -n 1 HEAD^2)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PREVIOUS_COMMIT=$(git log --format=%H -n 1 HEAD^2~1)" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Save PR number
        run: |
          mkdir -p ./maintainers
          echo ${{ github.event.number }} > ./maintainers/NR
      - name: Get Maintainers
        run: |
          echo "MAINTAINERS<<EOF" >> $GITHUB_ENV
          echo $(./toolset/github_actions/get_maintainers.py) > ./maintainers/maintainers.md
          echo "EOF" >> $GITHUB_ENV
      - name: Write Maintainers
        if: ${{ env.MAINTAINERS }}
        run: |
          echo ${{ env.MAINTAINERS }} > ./maintainers/maintainers.md
      - name: Save Maintainers
        if: ${{ env.MAINTAINERS }}
        uses: actions/upload-artifact@v3
        with:
          name: maintainers
          path: ./maintainers/
